### ISSUE TITLE
Copy Of This Site

### ISSUE THREAD

**Issue by VutonDesign** [Nanomotion/Nanomotion.github.io#1]
Hey! I just thought I'd let you know that someone seems to have made a copy of this site without forking or anything. Nothing has even been changed tbh & they seem to be doing the same for my stuff.

Copy link - https://torotv.github.io/

**Comment by Nanomotion** [comment]
Thanks for pointing this out. I've already asked the owner, as they've copied it to 3 different places of their own without changing it. They either don't know how to speak English properly, or they don't understand.

**Comment by VutonDesign** [comment]
@Nanomotion Yeah, Same here. I thought I would let you know just in case. I contacted github support to see if they can ask them to take it down as they seem to be ignoring us.

**Comment by Nanomotion** [comment]
@VutonDesign Thank you, here's the other copied link that I've found, from the same user. If you could add it to the support case, that would be great.
https://github.com/Strudy/Strudy.github.io

Also, I'm sure you know, but the user copied your site, as I saw your username in one of the files. https://github.com/Pixel-Flow/SiteBETA
https://github.com/Torotv/Vutondesign.github.io
https://github.com/Torotv/BetaTorotv
https://github.com/Torotv/site-archive

I noticed that they copied @BGMead's website too. https://github.com/Torotv/Pixel-Flow-Design

**Comment by VutonDesign** [comment]
@Nanomotion Yeah, They are all mine with changed names etc.

Thanks for this 👍

**Comment by Nanomotion** [comment]
@VutonDesign Alright, thanks. Let me know as things change.

**Comment by VutonDesign** [comment]
@Nanomotion Okay, Will do.

**Comment by VutonDesign** [comment]
@Nanomotion Github said that we should ask the user to take it down first through an Issue.

**Comment by Nanomotion** [comment]
@VutonDesign Do you mind giving me a screenshot of the response from GitHub so I can add it to the issue?

**Comment by VutonDesign** [comment]
@Nanomotion 
![untitled](https://user-images.githubusercontent.com/26391179/31099048-9e51b3d2-a7bc-11e7-9a56-66e9a6b22b40.png)

**Comment by Nanomotion** [comment]
@VutonDesign Thanks, I'll make the issue now.

**Comment by VutonDesign** [comment]
No Problem 👍

**Comment by Nanomotion** [comment]
Made it, waiting for them to respond. I'll give them 24 hours to respond.

**Comment by Nanomotion** [comment]
@VutonDesign They seem to have deleted the repo, thanks for your help.

**Comment by VutonDesign** [comment]
No Problem 😃

**Comment by GreenBayRules** [comment]
btw hes forked every single one of my repos xD and not changed a single thing

**Comment by Nanomotion** [comment]
It seems to be a common problem
