### ISSUE TITLE
Domain Question

### ISSUE THREAD

**Issue by vutondesign** [Nanomotion/Nanomotion.github.io#5]
I noticed you own nanomotion.xyz, and it is the exact same as Nanomotion.github.io, would It not just be better to use nanomotion.xyz everywhere?

**Comment by Nanomotion** [comment]
I mostly use nanomotion.xyz for backend things like oauth and there's no ssl support

**Comment by vutondesign** [comment]
Okay, but could you not use Cloudflare for SSL?

**Comment by Nanomotion** [comment]
Then I'd have to switch DNS providers

**Comment by vutondesign** [comment]
Yeah
